name: Building eBPF

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - uses: dtolnay/rust-toolchain@nightly
      with:
          components: rust-src

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Install bpf-linker
      run: |
        curl -LO https://github.com/aya-rs/bpf-linker/releases/latest/download/bpf-linker-x86_64-unknown-linux-musl.tar.zst
        tar --zstd -xvf bpf-linker-x86_64-unknown-linux-musl.tar.zst
        chmod +x bpf-linker
        sudo mv bpf-linker /usr/local/bin/

    - name: Build eBPF
      run: cargo build --manifest-path phage-agent/phage-agent-ebpf/Cargo.toml --target bpfel-unknown-none -Z build-std=core --release
    - name: Build eBPF builder
      run: cargo build --release --bin phage-agent -p phage-agent
